Repository ThesisVault/thesis-vault, pull requests merged in 2024-11, with the labels that each got.

#10 feat/LM-20-create-test-cases-for-landing-page
  .jestrc.json
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
  src/shared/components/__test__/common/footer.test.tsx
  src/shared/components/__test__/common/navigationBar.test.tsx
  src/shared/components/__test__/home/searchBar.test.tsx
  src/shared/components/common/Navigationbar.tsx
  tsconfig.json
Labels: Test

#32 feat/TV-27-create-permission-documentation
  src/docs/permission.md
Labels: Documentation

#37 [docs]: add updateUserPermission and updateUserRole use cases diagram
  .github/pull_request_template
  docs/architecture/permission.md
  docs/diagrams/user/useCase/udpateUserPermissionUseCase.sequence.md
  docs/diagrams/user/useCase/updateUserRoleUseCase.sequence.md
Labels: Documentation

#42 feat/TV-35-implement-updateUserRoleIdUseCase
  docs/diagrams/user/useCase/updateUserRoleIdUseCase.sequence.md
  docs/diagrams/user/useCase/updateUserRoleUseCase.sequence.md
  src/modules/user/src/domain/models/user/classes/user.ts
  src/modules/user/src/domain/models/user/constant.ts
  src/modules/user/src/dtos/userDTO.ts
  src/modules/user/src/infrastructure/http/controllers/updateUserRoleIdController.ts
  src/modules/user/src/mappers/userMapper.ts
  src/modules/user/src/useCases/updateUserRoleIdUseCase.ts
  src/modules/user/tests/infrastructure/http/controllers/updateUserRoleIdController.test.ts
  src/modules/user/tests/repositories/user/updateUser.test.ts
  src/modules/user/tests/repositories/user/updateUsers.test.ts
  src/modules/user/tests/useCases/updateUserRoleIdUseCase.test.ts
Labels: Feature

#45 feat/TV-43-test-updateUserPermissions-endpoint
  .jestrc.json
  babel.config.json
  docs/diagrams/user/useCase/updateUserPermissionUseCase.sequence.md
  docs/diagrams/user/useCase/updateUserRoleIdUseCase.sequence.md
  package.json
  pnpm-lock.yaml
  src/modules/user/src/infrastructure/http/controllers/user/updateUserPermissionController.ts
  src/modules/user/src/infrastructure/http/controllers/user/updateUserRoleIdController.ts
  src/modules/user/src/infrastructure/http/routes/user/userRouter.ts
  src/modules/user/tests/infrastructure/http/controllers/user/updateUserPermissionController.test.ts
  src/modules/user/tests/infrastructure/http/controllers/user/updateUserRoleIdController.test.ts
  src/modules/user/tests/infrastructure/http/routes/user/updateUserPermission.test.ts
  src/shared/core/errors.ts
  src/shared/infrastructure/trpc/routes.ts
Labels: Test

#49 feat/TV-44-implement-a-color-for-role
  prisma/schema.prisma
  src/modules/user/src/domain/models/role/classes/role.ts
  src/modules/user/src/domain/models/role/factory.ts
  src/modules/user/src/mappers/roleMapper.ts
  src/modules/user/tests/domain/models/role/classes/role.test.ts
  src/modules/user/tests/domain/models/role/factory.test.ts
  src/modules/user/tests/mappers/roleMapper.test.ts
  src/modules/user/tests/utils/role/createRoleDomainObject.ts
  src/modules/user/tests/utils/role/seedRole.ts
Labels: Feature
